spring:
  datasource:
    url: jdbc:mysql://localhost:3306/datastore?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: zhr100100
    driver-class-name: com.mysql.cj.jdbc.Driver


